name: Build & Deploy pipeline
run-name: "${{ github.actor }} triggered build & deploy for ${{ github.ref }}"
on:
  push:
    branches:
      - master
 
jobs:
  Build-and-Deploy:
    environment: master
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
 
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
 
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
 
      - name: Build Gradle project
        run: ./gradlew build
 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/*.jar
