name: Build & Deploy pipeline
run-name: "${{ github.actor }} triggered build & deploy for ${{ github.ref }}"
on:
  push:
    branches:
      - master
 
jobs:
  Build-and-Deploy:
    environment: master
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
 
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
 
      - name: Cache Maven and Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository/**
            ~/.gradle/caches/modules-2/files-2.1/**
          key: maven-gradle-cache-${{ hashFiles('~/.m2/repository/**', '~/.gradle/caches/modules-2/files-2.1/**') }}

      - name: Check Maven caching works
        run: du -cksh ~/.m2/repository
        continue-on-error: true
      
      - name: Check Gradle caching works
        run: du -cksh ~/.gradle/caches/modules-2/files-2.1
        continue-on-error: true

      - name: Build Maven project
        run: cd maven-project && mvn -B verify
 
      - name: Build Gradle project
        run: cd gradle-project && ./gradlew build
