name: Build & Deploy pipeline
run-name: "${{ github.actor }} triggered build & deploy for ${{ github.ref }}"
on:
  push:
    branches:
      - master
 
jobs:
  Build-and-Deploy:
    environment: master
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository/**
          key: maven-cache-${{ hashFiles('**/pom.xml') }}

      - name: Build Maven project
        run: mvn -B verify
