name: GitHub Actions Demo
run-name: "${{ github.actor }}: Deploy from ${{ github.ref }} to Github Pages"
on:
  push:
    branches:
      - master

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  Test-Build-Deploy-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: echo 'The secret is: ' ${{ secrets.CLOUDFLARE_API_TOKEN }}'
#       - run: npm ci
#       - run: npm run test:unit
#       - run: npm run build
#       - name: Publish to Cloudflare Pages
#         uses: cloudflare/pages-action@v1
#         with:
#           apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
#           accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
#           projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
#           directory: build/
