name: GitHub Actions Demo
run-name: "${{ github.actor }}: PR ${{ github.ref }}"
on: [pull_request]
jobs:
  Lint-Test-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit
